title: Welcome to Rokify
description: > # this means to ignore newlines until "baseurl:"
  Rokify is your go-to platform for discovering and reviewing the best products online. As a dedicated product review website, we specialize in providing honest, in-depth reviews of products featured on TradeTracker. Our mission is to help you make informed purchasing decisions by offering expert insights, user ratings, and comprehensive comparisons. Whether you're searching for the latest tech gadgets, home essentials, or lifestyle products, Rokify ensures you have all the information you need to choose wisely.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.rokify.nl" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Rokify # add your name
author-img: rokify.png # add your photo
about-author: We are a team of product enthusiasts dedicated to helping you find the best products online. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: 'G-HH3C4JKF49' # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
